apiVersion: v1
kind: Service
metadata:
  name: {{ include "cf-yaci-devkit.fullname" . }}-viewer
  labels:
    {{- include "cf-yaci-devkit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.viewer.service.type }}
  ports:
    - port: {{ .Values.viewer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cf-yaci-devkit.viewer.selectorLabels" . | nindent 4 }}
